// Code generated by go generate; DO NOT EDIT.
// This code was generated by robots at
// 2017-11-27 15:42:32.468927357 +1100 AEDT m=+0.020706795

package ffmpeg

type Codec int

const (
	Codec012V             Codec = iota // Uncompressed 4:2:2 10-bit
	Codec4Xm                           // 4X Movie
	Codec8Bps                          // QuickTime 8BPS video
	CodecA64Multi                      // Multicolor charset for Commodore 64 (encoders: a64multi )
	CodecA64Multi5                     // Multicolor charset for Commodore 64, extended with 5th color (colram) (encoders: a64multi5 )
	CodecAasc                          // Autodesk RLE
	CodecAic                           // Apple Intermediate Codec
	CodecAliasPix                      // Alias/Wavefront PIX image
	CodecAmv                           // AMV Video
	CodecAnm                           // Deluxe Paint Animation
	CodecAnsi                          // ASCII/ANSI art
	CodecApng                          // APNG (Animated Portable Network Graphics) image
	CodecAsv1                          // ASUS V1
	CodecAsv2                          // ASUS V2
	CodecAura                          // Auravision AURA
	CodecAura2                         // Auravision Aura 2
	CodecAv1                           // Alliance for Open Media AV1
	CodecAvrn                          // Avid AVI Codec
	CodecAvrp                          // Avid 1:1 10-bit RGB Packer
	CodecAvs                           // AVS (Audio Video Standard) video
	CodecAvui                          // Avid Meridien Uncompressed
	CodecAyuv                          // Uncompressed packed MS 4:4:4:4
	CodecBethsoftvid                   // Bethesda VID video
	CodecBfi                           // Brute Force & Ignorance
	CodecBinkvideo                     // Bink video
	CodecBintext                       // Binary text
	CodecBitpacked                     // Bitpacked
	CodecBmp                           // BMP (Windows and OS/2 bitmap)
	CodecBmvVideo                      // Discworld II BMV video
	CodecBrenderPix                    // BRender PIX image
	CodecC93                           // Interplay C93
	CodecCavs                          // Chinese AVS (Audio Video Standard) (AVS1-P2, JiZhun profile)
	CodecCdgraphics                    // CD Graphics video
	CodecCdxl                          // Commodore CDXL video
	CodecCfhd                          // Cineform HD
	CodecCinepak                       // Cinepak
	CodecClearvideo                    // Iterated Systems ClearVideo
	CodecCljr                          // Cirrus Logic AccuPak
	CodecCllc                          // Canopus Lossless Codec
	CodecCmv                           // Electronic Arts CMV video (decoders: eacmv )
	CodecCpia                          // CPiA video format
	CodecCscd                          // CamStudio (decoders: camstudio )
	CodecCyuv                          // Creative YUV (CYUV)
	CodecDaala                         // Daala
	CodecDds                           // DirectDraw Surface image decoder
	CodecDfa                           // Chronomaster DFA
	CodecDirac                         // Dirac (encoders: vc2 )
	CodecDnxhd                         // VC3/DNxHD
	CodecDpx                           // DPX (Digital Picture Exchange) image
	CodecDsicinvideo                   // Delphine Software International CIN video
	CodecDvvideo                       // DV (Digital Video)
	CodecDxa                           // Feeble Files/ScummVM DXA
	CodecDxtory                        // Dxtory
	CodecDxv                           // Resolume DXV
	CodecEscape124                     // Escape 124
	CodecEscape130                     // Escape 130
	CodecExr                           // OpenEXR image
	CodecFfv1                          // FFmpeg video codec #1
	CodecFfvhuff                       // Huffyuv FFmpeg variant
	CodecFic                           // Mirillis FIC
	CodecFits                          // FITS (Flexible Image Transport System)
	CodecFlashsv                       // Flash Screen Video v1
	CodecFlashsv2                      // Flash Screen Video v2
	CodecFlic                          // Autodesk Animator Flic video
	CodecFlv1                          // FLV / Sorenson Spark / Sorenson H.263 (Flash Video) (decoders: flv ) (encoders: flv )
	CodecFmvc                          // FM Screen Capture Codec
	CodecFraps                         // Fraps
	CodecFrwu                          // Forward Uncompressed
	CodecG2M                           // Go2Meeting
	CodecGdv                           // Gremlin Digital Video
	CodecGif                           // GIF (Graphics Interchange Format)
	CodecH261                          // H.261
	CodecH263                          // H.263 / H.263-1996, H.263+ / H.263-1998 / H.263 version 2
	CodecH263I                         // Intel H.263
	CodecH263P                         // H.263+ / H.263-1998 / H.263 version 2
	CodecH264                          // H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (encoders: libx264 libx264rgb h264_videotoolbox )
	CodecHap                           // Vidvox Hap
	CodecHevc                          // H.265 / HEVC (High Efficiency Video Coding)
	CodecHnm4Video                     // HNM 4 video
	CodecHqHqa                         // Canopus HQ/HQA
	CodecHqx                           // Canopus HQX
	CodecHuffyuv                       // HuffYUV
	CodecIdcin                         // id Quake II CIN video (decoders: idcinvideo )
	CodecIdf                           // iCEDraw text
	CodecIffIlbm                       // IFF ACBM/ANIM/DEEP/ILBM/PBM/RGB8/RGBN (decoders: iff )
	CodecIndeo2                        // Intel Indeo 2
	CodecIndeo3                        // Intel Indeo 3
	CodecIndeo4                        // Intel Indeo Video Interactive 4
	CodecIndeo5                        // Intel Indeo Video Interactive 5
	CodecInterplayvideo                // Interplay MVE video
	CodecJpeg2000                      // JPEG 2000
	CodecJpegls                        // JPEG-LS
	CodecJv                            // Bitmap Brothers JV video
	CodecKgv1                          // Kega Game Video
	CodecKmvc                          // Karl Morton's video codec
	CodecLagarith                      // Lagarith lossless
	CodecLjpeg                         // Lossless JPEG
	CodecLoco                          // LOCO
	CodecM101                          // Matrox Uncompressed SD
	CodecMad                           // Electronic Arts Madcow Video (decoders: eamad )
	CodecMagicyuv                      // MagicYUV video
	CodecMdec                          // Sony PlayStation MDEC (Motion DECoder)
	CodecMimic                         // Mimic
	CodecMjpeg                         // Motion JPEG
	CodecMjpegb                        // Apple MJPEG-B
	CodecMmvideo                       // American Laser Games MM Video
	CodecMotionpixels                  // Motion Pixels video
	CodecMpeg1Video                    // MPEG-1 video
	CodecMpeg2Video                    // MPEG-2 video (decoders: mpeg2video mpegvideo )
	CodecMpeg4                         // MPEG-4 part 2 (encoders: mpeg4 libxvid )
	CodecMpegvideoXvmc                 // MPEG-1/2 video XvMC (X-Video Motion Compensation)
	CodecMsa1                          // MS ATC Screen
	CodecMscc                          // Mandsoft Screen Capture Codec
	CodecMsmpeg4V1                     // MPEG-4 part 2 Microsoft variant version 1
	CodecMsmpeg4V2                     // MPEG-4 part 2 Microsoft variant version 2
	CodecMsmpeg4V3                     // MPEG-4 part 2 Microsoft variant version 3 (decoders: msmpeg4 ) (encoders: msmpeg4 )
	CodecMsrle                         // Microsoft RLE
	CodecMss1                          // MS Screen 1
	CodecMss2                          // MS Windows Media Video V9 Screen
	CodecMsvideo1                      // Microsoft Video 1
	CodecMszh                          // LCL (LossLess Codec Library) MSZH
	CodecMts2                          // MS Expression Encoder Screen
	CodecMvc1                          // Silicon Graphics Motion Video Compressor 1
	CodecMvc2                          // Silicon Graphics Motion Video Compressor 2
	CodecMxpeg                         // Mobotix MxPEG video
	CodecNuv                           // NuppelVideo/RTJPEG
	CodecPafVideo                      // Amazing Studio Packed Animation File Video
	CodecPam                           // PAM (Portable AnyMap) image
	CodecPbm                           // PBM (Portable BitMap) image
	CodecPcx                           // PC Paintbrush PCX image
	CodecPgm                           // PGM (Portable GrayMap) image
	CodecPgmyuv                        // PGMYUV (Portable GrayMap YUV) image
	CodecPictor                        // Pictor/PC Paint
	CodecPixlet                        // Apple Pixlet
	CodecPng                           // PNG (Portable Network Graphics) image
	CodecPpm                           // PPM (Portable PixelMap) image
	CodecProres                        // Apple ProRes (iCodec Pro) (decoders: prores prores_lgpl ) (encoders: prores prores_aw prores_ks )
	CodecPsd                           // Photoshop PSD file
	CodecPtx                           // V.Flash PTX image
	CodecQdraw                         // Apple QuickDraw
	CodecQpeg                          // Q-team QPEG
	CodecQtrle                         // QuickTime Animation (RLE) video
	CodecR10K                          // AJA Kona 10-bit RGB Codec
	CodecR210                          // Uncompressed RGB 10-bit
	CodecRawvideo                      // raw video
	CodecRl2                           // RL2 video
	CodecRoq                           // id RoQ video (decoders: roqvideo ) (encoders: roqvideo )
	CodecRpza                          // QuickTime video (RPZA)
	CodecRscc                          // innoHeim/Rsupport Screen Capture Codec
	CodecRv10                          // RealVideo 1.0
	CodecRv20                          // RealVideo 2.0
	CodecRv30                          // RealVideo 3.0
	CodecRv40                          // RealVideo 4.0
	CodecSanm                          // LucasArts SANM/SMUSH video
	CodecScpr                          // ScreenPressor
	CodecScreenpresso                  // Screenpresso
	CodecSgi                           // SGI image
	CodecSgirle                        // SGI RLE 8-bit
	CodecSheervideo                    // BitJazz SheerVideo
	CodecSmackvideo                    // Smacker video (decoders: smackvid )
	CodecSmc                           // QuickTime Graphics (SMC)
	CodecSmvjpeg                       // Sigmatel Motion Video
	CodecSnow                          // Snow
	CodecSp5X                          // Sunplus JPEG (SP5X)
	CodecSpeedhq                       // NewTek SpeedHQ
	CodecSrgc                          // Screen Recorder Gold Codec
	CodecSunrast                       // Sun Rasterfile image
	CodecSvg                           // Scalable Vector Graphics
	CodecSvq1                          // Sorenson Vector Quantizer 1 / Sorenson Video 1 / SVQ1
	CodecSvq3                          // Sorenson Vector Quantizer 3 / Sorenson Video 3 / SVQ3
	CodecTarga                         // Truevision Targa image
	CodecTargaY216                     // Pinnacle TARGA CineWave YUV16
	CodecTdsc                          // TDSC
	CodecTgq                           // Electronic Arts TGQ video (decoders: eatgq )
	CodecTgv                           // Electronic Arts TGV video (decoders: eatgv )
	CodecTheora                        // Theora
	CodecThp                           // Nintendo Gamecube THP video
	CodecTiertexseqvideo               // Tiertex Limited SEQ video
	CodecTiff                          // TIFF image
	CodecTmv                           // 8088flex TMV
	CodecTqi                           // Electronic Arts TQI video (decoders: eatqi )
	CodecTruemotion1                   // Duck TrueMotion 1.0
	CodecTruemotion2                   // Duck TrueMotion 2.0
	CodecTruemotion2Rt                 // Duck TrueMotion 2.0 Real Time
	CodecTscc                          // TechSmith Screen Capture Codec (decoders: camtasia )
	CodecTscc2                         // TechSmith Screen Codec 2
	CodecTxd                           // Renderware TXD (TeXture Dictionary) image
	CodecUlti                          // IBM UltiMotion (decoders: ultimotion )
	CodecUtvideo                       // Ut Video
	CodecV210                          // Uncompressed 4:2:2 10-bit
	CodecV210X                         // Uncompressed 4:2:2 10-bit
	CodecV308                          // Uncompressed packed 4:4:4
	CodecV408                          // Uncompressed packed QT 4:4:4:4
	CodecV410                          // Uncompressed 4:4:4 10-bit
	CodecVb                            // Beam Software VB
	CodecVble                          // VBLE Lossless Codec
	CodecVc1                           // SMPTE VC-1
	CodecVc1Image                      // Windows Media Video 9 Image v2
	CodecVcr1                          // ATI VCR1
	CodecVixl                          // Miro VideoXL (decoders: xl )
	CodecVmdvideo                      // Sierra VMD video
	CodecVmnc                          // VMware Screen Codec / VMware Video
	CodecVp3                           // On2 VP3
	CodecVp5                           // On2 VP5
	CodecVp6                           // On2 VP6
	CodecVp6A                          // On2 VP6 (Flash version, with alpha channel)
	CodecVp6F                          // On2 VP6 (Flash version)
	CodecVp7                           // On2 VP7
	CodecVp8                           // On2 VP8
	CodecVp9                           // Google VP9
	CodecWebp                          // WebP
	CodecWmv1                          // Windows Media Video 7
	CodecWmv2                          // Windows Media Video 8
	CodecWmv3                          // Windows Media Video 9
	CodecWmv3Image                     // Windows Media Video 9 Image
	CodecWnv1                          // Winnov WNV1
	CodecWrappedAvframe                // AVFrame to AVPacket passthrough
	CodecWsVqa                         // Westwood Studios VQA (Vector Quantized Animation) video (decoders: vqavideo )
	CodecXanWc3                        // Wing Commander III / Xan
	CodecXanWc4                        // Wing Commander IV / Xxan
	CodecXbin                          // eXtended BINary text
	CodecXbm                           // XBM (X BitMap) image
	CodecXface                         // X-face image
	CodecXpm                           // XPM (X PixMap) image
	CodecXwd                           // XWD (X Window Dump) image
	CodecY41P                          // Uncompressed YUV 4:1:1 12-bit
	CodecYlc                           // YUY2 Lossless Codec
	CodecYop                           // Psygnosis YOP Video
	CodecYuv4                          // Uncompressed packed 4:2:0
	CodecZerocodec                     // ZeroCodec Lossless Video
	CodecZlib                          // LCL (LossLess Codec Library) ZLIB
	CodecZmbv                          // Zip Motion Blocks Video
	Codec4Gv                           // 4GV (Fourth Generation Vocoder)
	Codec8SvxExp                       // 8SVX exponential
	Codec8SvxFib                       // 8SVX fibonacci
	CodecAac                           // AAC (Advanced Audio Coding) (decoders: aac aac_fixed aac_at ) (encoders: aac aac_at )
	CodecAacLatm                       // AAC LATM (Advanced Audio Coding LATM syntax)
	CodecAc3                           // ATSC A/52A (AC-3) (decoders: ac3 ac3_fixed ac3_at ) (encoders: ac3 ac3_fixed )
	CodecAdpcm4Xm                      // ADPCM 4X Movie
	CodecAdpcmAdx                      // SEGA CRI ADX ADPCM
	CodecAdpcmAfc                      // ADPCM Nintendo Gamecube AFC
	CodecAdpcmAica                     // ADPCM Yamaha AICA
	CodecAdpcmCt                       // ADPCM Creative Technology
	CodecAdpcmDtk                      // ADPCM Nintendo Gamecube DTK
	CodecAdpcmEa                       // ADPCM Electronic Arts
	CodecAdpcmEaMaxisXa                // ADPCM Electronic Arts Maxis CDROM XA
	CodecAdpcmEaR1                     // ADPCM Electronic Arts R1
	CodecAdpcmEaR2                     // ADPCM Electronic Arts R2
	CodecAdpcmEaR3                     // ADPCM Electronic Arts R3
	CodecAdpcmEaXas                    // ADPCM Electronic Arts XAS
	CodecAdpcmG722                     // G.722 ADPCM (decoders: g722 ) (encoders: g722 )
	CodecAdpcmG726                     // G.726 ADPCM (decoders: g726 ) (encoders: g726 )
	CodecAdpcmG726Le                   // G.726 ADPCM little-endian (decoders: g726le ) (encoders: g726le )
	CodecAdpcmImaAmv                   // ADPCM IMA AMV
	CodecAdpcmImaApc                   // ADPCM IMA CRYO APC
	CodecAdpcmImaDat4                  // ADPCM IMA Eurocom DAT4
	CodecAdpcmImaDk3                   // ADPCM IMA Duck DK3
	CodecAdpcmImaDk4                   // ADPCM IMA Duck DK4
	CodecAdpcmImaEaEacs                // ADPCM IMA Electronic Arts EACS
	CodecAdpcmImaEaSead                // ADPCM IMA Electronic Arts SEAD
	CodecAdpcmImaIss                   // ADPCM IMA Funcom ISS
	CodecAdpcmImaOki                   // ADPCM IMA Dialogic OKI
	CodecAdpcmImaQt                    // ADPCM IMA QuickTime (decoders: adpcm_ima_qt adpcm_ima_qt_at )
	CodecAdpcmImaRad                   // ADPCM IMA Radical
	CodecAdpcmImaSmjpeg                // ADPCM IMA Loki SDL MJPEG
	CodecAdpcmImaWav                   // ADPCM IMA WAV
	CodecAdpcmImaWs                    // ADPCM IMA Westwood
	CodecAdpcmMs                       // ADPCM Microsoft
	CodecAdpcmMtaf                     // ADPCM MTAF
	CodecAdpcmPsx                      // ADPCM Playstation
	CodecAdpcmSbpro2                   // ADPCM Sound Blaster Pro 2-bit
	CodecAdpcmSbpro3                   // ADPCM Sound Blaster Pro 2.6-bit
	CodecAdpcmSbpro4                   // ADPCM Sound Blaster Pro 4-bit
	CodecAdpcmSwf                      // ADPCM Shockwave Flash
	CodecAdpcmThp                      // ADPCM Nintendo THP
	CodecAdpcmThpLe                    // ADPCM Nintendo THP (Little-Endian)
	CodecAdpcmVima                     // LucasArts VIMA audio
	CodecAdpcmXa                       // ADPCM CDROM XA
	CodecAdpcmYamaha                   // ADPCM Yamaha
	CodecAlac                          // ALAC (Apple Lossless Audio Codec) (decoders: alac alac_at ) (encoders: alac alac_at )
	CodecAmrNb                         // AMR-NB (Adaptive Multi-Rate NarrowBand) (decoders: amrnb amr_nb_at )
	CodecAmrWb                         // AMR-WB (Adaptive Multi-Rate WideBand) (decoders: amrwb )
	CodecApe                           // Monkey's Audio
	CodecAtrac1                        // ATRAC1 (Adaptive TRansform Acoustic Coding)
	CodecAtrac3                        // ATRAC3 (Adaptive TRansform Acoustic Coding 3)
	CodecAtrac3Al                      // ATRAC3 AL (Adaptive TRansform Acoustic Coding 3 Advanced Lossless)
	CodecAtrac3P                       // ATRAC3+ (Adaptive TRansform Acoustic Coding 3+) (decoders: atrac3plus )
	CodecAtrac3Pal                     // ATRAC3+ AL (Adaptive TRansform Acoustic Coding 3+ Advanced Lossless) (decoders: atrac3plusal )
	CodecAvc                           // On2 Audio for Video Codec (decoders: on2avc )
	CodecBinkaudioDct                  // Bink Audio (DCT)
	CodecBinkaudioRdft                 // Bink Audio (RDFT)
	CodecBmvAudio                      // Discworld II BMV audio
	CodecCelt                          // Constrained Energy Lapped Transform (CELT)
	CodecComfortnoise                  // RFC 3389 Comfort Noise
	CodecCook                          // Cook / Cooker / Gecko (RealAudio G2)
	CodecDolbyE                        // Dolby E
	CodecDsdLsbf                       // DSD (Direct Stream Digital), least significant bit first
	CodecDsdLsbfPlanar                 // DSD (Direct Stream Digital), least significant bit first, planar
	CodecDsdMsbf                       // DSD (Direct Stream Digital), most significant bit first
	CodecDsdMsbfPlanar                 // DSD (Direct Stream Digital), most significant bit first, planar
	CodecDsicinaudio                   // Delphine Software International CIN audio
	CodecDssSp                         // Digital Speech Standard - Standard Play mode (DSS SP)
	CodecDst                           // DST (Direct Stream Transfer)
	CodecDts                           // DCA (DTS Coherent Acoustics) (decoders: dca ) (encoders: dca )
	CodecDvaudio                       // DV audio
	CodecEac3                          // ATSC A/52B (AC-3, E-AC-3) (decoders: eac3 eac3_at )
	CodecEvrc                          // EVRC (Enhanced Variable Rate Codec)
	CodecFlac                          // FLAC (Free Lossless Audio Codec)
	CodecG7231                         // G.723.1
	CodecG729                          // G.729
	CodecGremlinDpcm                   // DPCM Gremlin
	CodecGsm                           // GSM
	CodecGsmMs                         // GSM Microsoft variant (decoders: gsm_ms gsm_ms_at )
	CodecIac                           // IAC (Indeo Audio Coder)
	CodecIlbc                          // iLBC (Internet Low Bitrate Codec) (decoders: ilbc_at ) (encoders: ilbc_at )
	CodecImc                           // IMC (Intel Music Coder)
	CodecInterplayDpcm                 // DPCM Interplay
	CodecInterplayacm                  // Interplay ACM
	CodecMace3                         // MACE (Macintosh Audio Compression/Expansion) 3:1
	CodecMace6                         // MACE (Macintosh Audio Compression/Expansion) 6:1
	CodecMetasound                     // Voxware MetaSound
	CodecMlp                           // MLP (Meridian Lossless Packing)
	CodecMp1                           // MP1 (MPEG audio layer 1) (decoders: mp1 mp1float mp1_at )
	CodecMp2                           // MP2 (MPEG audio layer 2) (decoders: mp2 mp2float mp2_at ) (encoders: mp2 mp2fixed )
	CodecMp3                           // MP3 (MPEG audio layer 3) (decoders: mp3 mp3float mp3_at ) (encoders: libmp3lame )
	CodecMp3Adu                        // ADU (Application Data Unit) MP3 (MPEG audio layer 3) (decoders: mp3adu mp3adufloat )
	CodecMp3On4                        // MP3onMP4 (decoders: mp3on4 mp3on4float )
	CodecMp4Als                        // MPEG-4 Audio Lossless Coding (ALS) (decoders: als )
	CodecMusepack7                     // Musepack SV7 (decoders: mpc7 )
	CodecMusepack8                     // Musepack SV8 (decoders: mpc8 )
	CodecNellymoser                    // Nellymoser Asao
	CodecOpus                          // Opus (Opus Interactive Audio Codec)
	CodecPafAudio                      // Amazing Studio Packed Animation File Audio
	CodecPcmAlaw                       // PCM A-law / G.711 A-law (decoders: pcm_alaw pcm_alaw_at ) (encoders: pcm_alaw pcm_alaw_at )
	CodecPcmBluray                     // PCM signed 16|20|24-bit big-endian for Blu-ray media
	CodecPcmDvd                        // PCM signed 20|24-bit big-endian
	CodecPcmF16Le                      // PCM 16.8 floating point little-endian
	CodecPcmF24Le                      // PCM 24.0 floating point little-endian
	CodecPcmF32Be                      // PCM 32-bit floating point big-endian
	CodecPcmF32Le                      // PCM 32-bit floating point little-endian
	CodecPcmF64Be                      // PCM 64-bit floating point big-endian
	CodecPcmF64Le                      // PCM 64-bit floating point little-endian
	CodecPcmLxf                        // PCM signed 20-bit little-endian planar
	CodecPcmMulaw                      // PCM mu-law / G.711 mu-law (decoders: pcm_mulaw pcm_mulaw_at ) (encoders: pcm_mulaw pcm_mulaw_at )
	CodecPcmS16Be                      // PCM signed 16-bit big-endian
	CodecPcmS16BePlanar                // PCM signed 16-bit big-endian planar
	CodecPcmS16Le                      // PCM signed 16-bit little-endian
	CodecPcmS16LePlanar                // PCM signed 16-bit little-endian planar
	CodecPcmS24Be                      // PCM signed 24-bit big-endian
	CodecPcmS24Daud                    // PCM D-Cinema audio signed 24-bit
	CodecPcmS24Le                      // PCM signed 24-bit little-endian
	CodecPcmS24LePlanar                // PCM signed 24-bit little-endian planar
	CodecPcmS32Be                      // PCM signed 32-bit big-endian
	CodecPcmS32Le                      // PCM signed 32-bit little-endian
	CodecPcmS32LePlanar                // PCM signed 32-bit little-endian planar
	CodecPcmS64Be                      // PCM signed 64-bit big-endian
	CodecPcmS64Le                      // PCM signed 64-bit little-endian
	CodecPcmS8                         // PCM signed 8-bit
	CodecPcmS8Planar                   // PCM signed 8-bit planar
	CodecPcmU16Be                      // PCM unsigned 16-bit big-endian
	CodecPcmU16Le                      // PCM unsigned 16-bit little-endian
	CodecPcmU24Be                      // PCM unsigned 24-bit big-endian
	CodecPcmU24Le                      // PCM unsigned 24-bit little-endian
	CodecPcmU32Be                      // PCM unsigned 32-bit big-endian
	CodecPcmU32Le                      // PCM unsigned 32-bit little-endian
	CodecPcmU8                         // PCM unsigned 8-bit
	CodecPcmZork                       // PCM Zork
	CodecQcelp                         // QCELP / PureVoice
	CodecQdm2                          // QDesign Music Codec 2 (decoders: qdm2 qdm2_at )
	CodecQdmc                          // QDesign Music (decoders: qdmc qdmc_at )
	CodecRa144                         // RealAudio 1.0 (14.4K) (decoders: real_144 ) (encoders: real_144 )
	CodecRa288                         // RealAudio 2.0 (28.8K) (decoders: real_288 )
	CodecRalf                          // RealAudio Lossless
	CodecRoqDpcm                       // DPCM id RoQ
	CodecS302M                         // SMPTE 302M
	CodecSdx2Dpcm                      // DPCM Squareroot-Delta-Exact
	CodecShorten                       // Shorten
	CodecSipr                          // RealAudio SIPR / ACELP.NET
	CodecSmackaudio                    // Smacker audio (decoders: smackaud )
	CodecSmv                           // SMV (Selectable Mode Vocoder)
	CodecSolDpcm                       // DPCM Sol
	CodecSonic                         // Sonic
	CodecSonicls                       // Sonic lossless
	CodecSpeex                         // Speex
	CodecTak                           // TAK (Tom's lossless Audio Kompressor)
	CodecTruehd                        // TrueHD
	CodecTruespeech                    // DSP Group TrueSpeech
	CodecTta                           // TTA (True Audio)
	CodecTwinvq                        // VQF TwinVQ
	CodecVmdaudio                      // Sierra VMD audio
	CodecVorbis                        // Vorbis
	CodecVoxware                       // Voxware RT29 Metasound
	CodecWavesynth                     // Wave synthesis pseudo-codec
	CodecWavpack                       // WavPack
	CodecWestwoodSnd1                  // Westwood Audio (SND1) (decoders: ws_snd1 )
	CodecWmalossless                   // Windows Media Audio Lossless
	CodecWmapro                        // Windows Media Audio 9 Professional
	CodecWmav1                         // Windows Media Audio 1
	CodecWmav2                         // Windows Media Audio 2
	CodecWmavoice                      // Windows Media Audio Voice
	CodecXanDpcm                       // DPCM Xan
	CodecXma1                          // Xbox Media Audio 1
	CodecXma2                          // Xbox Media Audio 2
	CodecBinData                       // binary data
	CodecDvdNavPacket                  // DVD Nav packet
	CodecKlv                           // SMPTE 336M Key-Length-Value (KLV) metadata
	CodecOtf                           // OpenType font
	CodecScte35                        // SCTE 35 Message Queue
	CodecTimedId3                      // timed ID3 metadata
	CodecTtf                           // TrueType font
	CodecAss                           // ASS (Advanced SSA) subtitle (decoders: ssa ass ) (encoders: ssa ass )
	CodecDvbSubtitle                   // DVB subtitles (decoders: dvbsub ) (encoders: dvbsub )
	CodecDvbTeletext                   // DVB teletext
	CodecDvdSubtitle                   // DVD subtitles (decoders: dvdsub ) (encoders: dvdsub )
	CodecEia608                        // EIA-608 closed captions (decoders: cc_dec )
	CodecHdmvPgsSubtitle               // HDMV Presentation Graphic Stream subtitles (decoders: pgssub )
	CodecHdmvTextSubtitle              // HDMV Text subtitle
	CodecJacosub                       // JACOsub subtitle
	CodecMicrodvd                      // MicroDVD subtitle
	CodecMovText                       // MOV text
	CodecMpl2                          // MPL2 subtitle
	CodecPjs                           // PJS (Phoenix Japanimation Society) subtitle
	CodecRealtext                      // RealText subtitle
	CodecSami                          // SAMI subtitle
	CodecSrt                           // SubRip subtitle with embedded timing
	CodecSsa                           // SSA (SubStation Alpha) subtitle
	CodecStl                           // Spruce subtitle format
	CodecSubrip                        // SubRip subtitle (decoders: srt subrip ) (encoders: srt subrip )
	CodecSubviewer                     // SubViewer subtitle
	CodecSubviewer1                    // SubViewer v1 subtitle
	CodecText                          // raw UTF-8 text
	CodecVplayer                       // VPlayer subtitle
	CodecWebvtt                        // WebVTT subtitle
	CodecXsub                          // XSUB
)

func (typ Codec) String() string {
	switch typ {
	case Codec012V:
		return "012v"
	case Codec4Xm:
		return "4xm"
	case Codec8Bps:
		return "8bps"
	case CodecA64Multi:
		return "a64_multi"
	case CodecA64Multi5:
		return "a64_multi5"
	case CodecAasc:
		return "aasc"
	case CodecAic:
		return "aic"
	case CodecAliasPix:
		return "alias_pix"
	case CodecAmv:
		return "amv"
	case CodecAnm:
		return "anm"
	case CodecAnsi:
		return "ansi"
	case CodecApng:
		return "apng"
	case CodecAsv1:
		return "asv1"
	case CodecAsv2:
		return "asv2"
	case CodecAura:
		return "aura"
	case CodecAura2:
		return "aura2"
	case CodecAv1:
		return "av1"
	case CodecAvrn:
		return "avrn"
	case CodecAvrp:
		return "avrp"
	case CodecAvs:
		return "avs"
	case CodecAvui:
		return "avui"
	case CodecAyuv:
		return "ayuv"
	case CodecBethsoftvid:
		return "bethsoftvid"
	case CodecBfi:
		return "bfi"
	case CodecBinkvideo:
		return "binkvideo"
	case CodecBintext:
		return "bintext"
	case CodecBitpacked:
		return "bitpacked"
	case CodecBmp:
		return "bmp"
	case CodecBmvVideo:
		return "bmv_video"
	case CodecBrenderPix:
		return "brender_pix"
	case CodecC93:
		return "c93"
	case CodecCavs:
		return "cavs"
	case CodecCdgraphics:
		return "cdgraphics"
	case CodecCdxl:
		return "cdxl"
	case CodecCfhd:
		return "cfhd"
	case CodecCinepak:
		return "cinepak"
	case CodecClearvideo:
		return "clearvideo"
	case CodecCljr:
		return "cljr"
	case CodecCllc:
		return "cllc"
	case CodecCmv:
		return "cmv"
	case CodecCpia:
		return "cpia"
	case CodecCscd:
		return "cscd"
	case CodecCyuv:
		return "cyuv"
	case CodecDaala:
		return "daala"
	case CodecDds:
		return "dds"
	case CodecDfa:
		return "dfa"
	case CodecDirac:
		return "dirac"
	case CodecDnxhd:
		return "dnxhd"
	case CodecDpx:
		return "dpx"
	case CodecDsicinvideo:
		return "dsicinvideo"
	case CodecDvvideo:
		return "dvvideo"
	case CodecDxa:
		return "dxa"
	case CodecDxtory:
		return "dxtory"
	case CodecDxv:
		return "dxv"
	case CodecEscape124:
		return "escape124"
	case CodecEscape130:
		return "escape130"
	case CodecExr:
		return "exr"
	case CodecFfv1:
		return "ffv1"
	case CodecFfvhuff:
		return "ffvhuff"
	case CodecFic:
		return "fic"
	case CodecFits:
		return "fits"
	case CodecFlashsv:
		return "flashsv"
	case CodecFlashsv2:
		return "flashsv2"
	case CodecFlic:
		return "flic"
	case CodecFlv1:
		return "flv1"
	case CodecFmvc:
		return "fmvc"
	case CodecFraps:
		return "fraps"
	case CodecFrwu:
		return "frwu"
	case CodecG2M:
		return "g2m"
	case CodecGdv:
		return "gdv"
	case CodecGif:
		return "gif"
	case CodecH261:
		return "h261"
	case CodecH263:
		return "h263"
	case CodecH263I:
		return "h263i"
	case CodecH263P:
		return "h263p"
	case CodecH264:
		return "h264"
	case CodecHap:
		return "hap"
	case CodecHevc:
		return "hevc"
	case CodecHnm4Video:
		return "hnm4video"
	case CodecHqHqa:
		return "hq_hqa"
	case CodecHqx:
		return "hqx"
	case CodecHuffyuv:
		return "huffyuv"
	case CodecIdcin:
		return "idcin"
	case CodecIdf:
		return "idf"
	case CodecIffIlbm:
		return "iff_ilbm"
	case CodecIndeo2:
		return "indeo2"
	case CodecIndeo3:
		return "indeo3"
	case CodecIndeo4:
		return "indeo4"
	case CodecIndeo5:
		return "indeo5"
	case CodecInterplayvideo:
		return "interplayvideo"
	case CodecJpeg2000:
		return "jpeg2000"
	case CodecJpegls:
		return "jpegls"
	case CodecJv:
		return "jv"
	case CodecKgv1:
		return "kgv1"
	case CodecKmvc:
		return "kmvc"
	case CodecLagarith:
		return "lagarith"
	case CodecLjpeg:
		return "ljpeg"
	case CodecLoco:
		return "loco"
	case CodecM101:
		return "m101"
	case CodecMad:
		return "mad"
	case CodecMagicyuv:
		return "magicyuv"
	case CodecMdec:
		return "mdec"
	case CodecMimic:
		return "mimic"
	case CodecMjpeg:
		return "mjpeg"
	case CodecMjpegb:
		return "mjpegb"
	case CodecMmvideo:
		return "mmvideo"
	case CodecMotionpixels:
		return "motionpixels"
	case CodecMpeg1Video:
		return "mpeg1video"
	case CodecMpeg2Video:
		return "mpeg2video"
	case CodecMpeg4:
		return "mpeg4"
	case CodecMpegvideoXvmc:
		return "mpegvideo_xvmc"
	case CodecMsa1:
		return "msa1"
	case CodecMscc:
		return "mscc"
	case CodecMsmpeg4V1:
		return "msmpeg4v1"
	case CodecMsmpeg4V2:
		return "msmpeg4v2"
	case CodecMsmpeg4V3:
		return "msmpeg4v3"
	case CodecMsrle:
		return "msrle"
	case CodecMss1:
		return "mss1"
	case CodecMss2:
		return "mss2"
	case CodecMsvideo1:
		return "msvideo1"
	case CodecMszh:
		return "mszh"
	case CodecMts2:
		return "mts2"
	case CodecMvc1:
		return "mvc1"
	case CodecMvc2:
		return "mvc2"
	case CodecMxpeg:
		return "mxpeg"
	case CodecNuv:
		return "nuv"
	case CodecPafVideo:
		return "paf_video"
	case CodecPam:
		return "pam"
	case CodecPbm:
		return "pbm"
	case CodecPcx:
		return "pcx"
	case CodecPgm:
		return "pgm"
	case CodecPgmyuv:
		return "pgmyuv"
	case CodecPictor:
		return "pictor"
	case CodecPixlet:
		return "pixlet"
	case CodecPng:
		return "png"
	case CodecPpm:
		return "ppm"
	case CodecProres:
		return "prores"
	case CodecPsd:
		return "psd"
	case CodecPtx:
		return "ptx"
	case CodecQdraw:
		return "qdraw"
	case CodecQpeg:
		return "qpeg"
	case CodecQtrle:
		return "qtrle"
	case CodecR10K:
		return "r10k"
	case CodecR210:
		return "r210"
	case CodecRawvideo:
		return "rawvideo"
	case CodecRl2:
		return "rl2"
	case CodecRoq:
		return "roq"
	case CodecRpza:
		return "rpza"
	case CodecRscc:
		return "rscc"
	case CodecRv10:
		return "rv10"
	case CodecRv20:
		return "rv20"
	case CodecRv30:
		return "rv30"
	case CodecRv40:
		return "rv40"
	case CodecSanm:
		return "sanm"
	case CodecScpr:
		return "scpr"
	case CodecScreenpresso:
		return "screenpresso"
	case CodecSgi:
		return "sgi"
	case CodecSgirle:
		return "sgirle"
	case CodecSheervideo:
		return "sheervideo"
	case CodecSmackvideo:
		return "smackvideo"
	case CodecSmc:
		return "smc"
	case CodecSmvjpeg:
		return "smvjpeg"
	case CodecSnow:
		return "snow"
	case CodecSp5X:
		return "sp5x"
	case CodecSpeedhq:
		return "speedhq"
	case CodecSrgc:
		return "srgc"
	case CodecSunrast:
		return "sunrast"
	case CodecSvg:
		return "svg"
	case CodecSvq1:
		return "svq1"
	case CodecSvq3:
		return "svq3"
	case CodecTarga:
		return "targa"
	case CodecTargaY216:
		return "targa_y216"
	case CodecTdsc:
		return "tdsc"
	case CodecTgq:
		return "tgq"
	case CodecTgv:
		return "tgv"
	case CodecTheora:
		return "theora"
	case CodecThp:
		return "thp"
	case CodecTiertexseqvideo:
		return "tiertexseqvideo"
	case CodecTiff:
		return "tiff"
	case CodecTmv:
		return "tmv"
	case CodecTqi:
		return "tqi"
	case CodecTruemotion1:
		return "truemotion1"
	case CodecTruemotion2:
		return "truemotion2"
	case CodecTruemotion2Rt:
		return "truemotion2rt"
	case CodecTscc:
		return "tscc"
	case CodecTscc2:
		return "tscc2"
	case CodecTxd:
		return "txd"
	case CodecUlti:
		return "ulti"
	case CodecUtvideo:
		return "utvideo"
	case CodecV210:
		return "v210"
	case CodecV210X:
		return "v210x"
	case CodecV308:
		return "v308"
	case CodecV408:
		return "v408"
	case CodecV410:
		return "v410"
	case CodecVb:
		return "vb"
	case CodecVble:
		return "vble"
	case CodecVc1:
		return "vc1"
	case CodecVc1Image:
		return "vc1image"
	case CodecVcr1:
		return "vcr1"
	case CodecVixl:
		return "vixl"
	case CodecVmdvideo:
		return "vmdvideo"
	case CodecVmnc:
		return "vmnc"
	case CodecVp3:
		return "vp3"
	case CodecVp5:
		return "vp5"
	case CodecVp6:
		return "vp6"
	case CodecVp6A:
		return "vp6a"
	case CodecVp6F:
		return "vp6f"
	case CodecVp7:
		return "vp7"
	case CodecVp8:
		return "vp8"
	case CodecVp9:
		return "vp9"
	case CodecWebp:
		return "webp"
	case CodecWmv1:
		return "wmv1"
	case CodecWmv2:
		return "wmv2"
	case CodecWmv3:
		return "wmv3"
	case CodecWmv3Image:
		return "wmv3image"
	case CodecWnv1:
		return "wnv1"
	case CodecWrappedAvframe:
		return "wrapped_avframe"
	case CodecWsVqa:
		return "ws_vqa"
	case CodecXanWc3:
		return "xan_wc3"
	case CodecXanWc4:
		return "xan_wc4"
	case CodecXbin:
		return "xbin"
	case CodecXbm:
		return "xbm"
	case CodecXface:
		return "xface"
	case CodecXpm:
		return "xpm"
	case CodecXwd:
		return "xwd"
	case CodecY41P:
		return "y41p"
	case CodecYlc:
		return "ylc"
	case CodecYop:
		return "yop"
	case CodecYuv4:
		return "yuv4"
	case CodecZerocodec:
		return "zerocodec"
	case CodecZlib:
		return "zlib"
	case CodecZmbv:
		return "zmbv"
	case Codec4Gv:
		return "4gv"
	case Codec8SvxExp:
		return "8svx_exp"
	case Codec8SvxFib:
		return "8svx_fib"
	case CodecAac:
		return "aac"
	case CodecAacLatm:
		return "aac_latm"
	case CodecAc3:
		return "ac3"
	case CodecAdpcm4Xm:
		return "adpcm_4xm"
	case CodecAdpcmAdx:
		return "adpcm_adx"
	case CodecAdpcmAfc:
		return "adpcm_afc"
	case CodecAdpcmAica:
		return "adpcm_aica"
	case CodecAdpcmCt:
		return "adpcm_ct"
	case CodecAdpcmDtk:
		return "adpcm_dtk"
	case CodecAdpcmEa:
		return "adpcm_ea"
	case CodecAdpcmEaMaxisXa:
		return "adpcm_ea_maxis_xa"
	case CodecAdpcmEaR1:
		return "adpcm_ea_r1"
	case CodecAdpcmEaR2:
		return "adpcm_ea_r2"
	case CodecAdpcmEaR3:
		return "adpcm_ea_r3"
	case CodecAdpcmEaXas:
		return "adpcm_ea_xas"
	case CodecAdpcmG722:
		return "adpcm_g722"
	case CodecAdpcmG726:
		return "adpcm_g726"
	case CodecAdpcmG726Le:
		return "adpcm_g726le"
	case CodecAdpcmImaAmv:
		return "adpcm_ima_amv"
	case CodecAdpcmImaApc:
		return "adpcm_ima_apc"
	case CodecAdpcmImaDat4:
		return "adpcm_ima_dat4"
	case CodecAdpcmImaDk3:
		return "adpcm_ima_dk3"
	case CodecAdpcmImaDk4:
		return "adpcm_ima_dk4"
	case CodecAdpcmImaEaEacs:
		return "adpcm_ima_ea_eacs"
	case CodecAdpcmImaEaSead:
		return "adpcm_ima_ea_sead"
	case CodecAdpcmImaIss:
		return "adpcm_ima_iss"
	case CodecAdpcmImaOki:
		return "adpcm_ima_oki"
	case CodecAdpcmImaQt:
		return "adpcm_ima_qt"
	case CodecAdpcmImaRad:
		return "adpcm_ima_rad"
	case CodecAdpcmImaSmjpeg:
		return "adpcm_ima_smjpeg"
	case CodecAdpcmImaWav:
		return "adpcm_ima_wav"
	case CodecAdpcmImaWs:
		return "adpcm_ima_ws"
	case CodecAdpcmMs:
		return "adpcm_ms"
	case CodecAdpcmMtaf:
		return "adpcm_mtaf"
	case CodecAdpcmPsx:
		return "adpcm_psx"
	case CodecAdpcmSbpro2:
		return "adpcm_sbpro_2"
	case CodecAdpcmSbpro3:
		return "adpcm_sbpro_3"
	case CodecAdpcmSbpro4:
		return "adpcm_sbpro_4"
	case CodecAdpcmSwf:
		return "adpcm_swf"
	case CodecAdpcmThp:
		return "adpcm_thp"
	case CodecAdpcmThpLe:
		return "adpcm_thp_le"
	case CodecAdpcmVima:
		return "adpcm_vima"
	case CodecAdpcmXa:
		return "adpcm_xa"
	case CodecAdpcmYamaha:
		return "adpcm_yamaha"
	case CodecAlac:
		return "alac"
	case CodecAmrNb:
		return "amr_nb"
	case CodecAmrWb:
		return "amr_wb"
	case CodecApe:
		return "ape"
	case CodecAtrac1:
		return "atrac1"
	case CodecAtrac3:
		return "atrac3"
	case CodecAtrac3Al:
		return "atrac3al"
	case CodecAtrac3P:
		return "atrac3p"
	case CodecAtrac3Pal:
		return "atrac3pal"
	case CodecAvc:
		return "avc"
	case CodecBinkaudioDct:
		return "binkaudio_dct"
	case CodecBinkaudioRdft:
		return "binkaudio_rdft"
	case CodecBmvAudio:
		return "bmv_audio"
	case CodecCelt:
		return "celt"
	case CodecComfortnoise:
		return "comfortnoise"
	case CodecCook:
		return "cook"
	case CodecDolbyE:
		return "dolby_e"
	case CodecDsdLsbf:
		return "dsd_lsbf"
	case CodecDsdLsbfPlanar:
		return "dsd_lsbf_planar"
	case CodecDsdMsbf:
		return "dsd_msbf"
	case CodecDsdMsbfPlanar:
		return "dsd_msbf_planar"
	case CodecDsicinaudio:
		return "dsicinaudio"
	case CodecDssSp:
		return "dss_sp"
	case CodecDst:
		return "dst"
	case CodecDts:
		return "dts"
	case CodecDvaudio:
		return "dvaudio"
	case CodecEac3:
		return "eac3"
	case CodecEvrc:
		return "evrc"
	case CodecFlac:
		return "flac"
	case CodecG7231:
		return "g723_1"
	case CodecG729:
		return "g729"
	case CodecGremlinDpcm:
		return "gremlin_dpcm"
	case CodecGsm:
		return "gsm"
	case CodecGsmMs:
		return "gsm_ms"
	case CodecIac:
		return "iac"
	case CodecIlbc:
		return "ilbc"
	case CodecImc:
		return "imc"
	case CodecInterplayDpcm:
		return "interplay_dpcm"
	case CodecInterplayacm:
		return "interplayacm"
	case CodecMace3:
		return "mace3"
	case CodecMace6:
		return "mace6"
	case CodecMetasound:
		return "metasound"
	case CodecMlp:
		return "mlp"
	case CodecMp1:
		return "mp1"
	case CodecMp2:
		return "mp2"
	case CodecMp3:
		return "mp3"
	case CodecMp3Adu:
		return "mp3adu"
	case CodecMp3On4:
		return "mp3on4"
	case CodecMp4Als:
		return "mp4als"
	case CodecMusepack7:
		return "musepack7"
	case CodecMusepack8:
		return "musepack8"
	case CodecNellymoser:
		return "nellymoser"
	case CodecOpus:
		return "opus"
	case CodecPafAudio:
		return "paf_audio"
	case CodecPcmAlaw:
		return "pcm_alaw"
	case CodecPcmBluray:
		return "pcm_bluray"
	case CodecPcmDvd:
		return "pcm_dvd"
	case CodecPcmF16Le:
		return "pcm_f16le"
	case CodecPcmF24Le:
		return "pcm_f24le"
	case CodecPcmF32Be:
		return "pcm_f32be"
	case CodecPcmF32Le:
		return "pcm_f32le"
	case CodecPcmF64Be:
		return "pcm_f64be"
	case CodecPcmF64Le:
		return "pcm_f64le"
	case CodecPcmLxf:
		return "pcm_lxf"
	case CodecPcmMulaw:
		return "pcm_mulaw"
	case CodecPcmS16Be:
		return "pcm_s16be"
	case CodecPcmS16BePlanar:
		return "pcm_s16be_planar"
	case CodecPcmS16Le:
		return "pcm_s16le"
	case CodecPcmS16LePlanar:
		return "pcm_s16le_planar"
	case CodecPcmS24Be:
		return "pcm_s24be"
	case CodecPcmS24Daud:
		return "pcm_s24daud"
	case CodecPcmS24Le:
		return "pcm_s24le"
	case CodecPcmS24LePlanar:
		return "pcm_s24le_planar"
	case CodecPcmS32Be:
		return "pcm_s32be"
	case CodecPcmS32Le:
		return "pcm_s32le"
	case CodecPcmS32LePlanar:
		return "pcm_s32le_planar"
	case CodecPcmS64Be:
		return "pcm_s64be"
	case CodecPcmS64Le:
		return "pcm_s64le"
	case CodecPcmS8:
		return "pcm_s8"
	case CodecPcmS8Planar:
		return "pcm_s8_planar"
	case CodecPcmU16Be:
		return "pcm_u16be"
	case CodecPcmU16Le:
		return "pcm_u16le"
	case CodecPcmU24Be:
		return "pcm_u24be"
	case CodecPcmU24Le:
		return "pcm_u24le"
	case CodecPcmU32Be:
		return "pcm_u32be"
	case CodecPcmU32Le:
		return "pcm_u32le"
	case CodecPcmU8:
		return "pcm_u8"
	case CodecPcmZork:
		return "pcm_zork"
	case CodecQcelp:
		return "qcelp"
	case CodecQdm2:
		return "qdm2"
	case CodecQdmc:
		return "qdmc"
	case CodecRa144:
		return "ra_144"
	case CodecRa288:
		return "ra_288"
	case CodecRalf:
		return "ralf"
	case CodecRoqDpcm:
		return "roq_dpcm"
	case CodecS302M:
		return "s302m"
	case CodecSdx2Dpcm:
		return "sdx2_dpcm"
	case CodecShorten:
		return "shorten"
	case CodecSipr:
		return "sipr"
	case CodecSmackaudio:
		return "smackaudio"
	case CodecSmv:
		return "smv"
	case CodecSolDpcm:
		return "sol_dpcm"
	case CodecSonic:
		return "sonic"
	case CodecSonicls:
		return "sonicls"
	case CodecSpeex:
		return "speex"
	case CodecTak:
		return "tak"
	case CodecTruehd:
		return "truehd"
	case CodecTruespeech:
		return "truespeech"
	case CodecTta:
		return "tta"
	case CodecTwinvq:
		return "twinvq"
	case CodecVmdaudio:
		return "vmdaudio"
	case CodecVorbis:
		return "vorbis"
	case CodecVoxware:
		return "voxware"
	case CodecWavesynth:
		return "wavesynth"
	case CodecWavpack:
		return "wavpack"
	case CodecWestwoodSnd1:
		return "westwood_snd1"
	case CodecWmalossless:
		return "wmalossless"
	case CodecWmapro:
		return "wmapro"
	case CodecWmav1:
		return "wmav1"
	case CodecWmav2:
		return "wmav2"
	case CodecWmavoice:
		return "wmavoice"
	case CodecXanDpcm:
		return "xan_dpcm"
	case CodecXma1:
		return "xma1"
	case CodecXma2:
		return "xma2"
	case CodecBinData:
		return "bin_data"
	case CodecDvdNavPacket:
		return "dvd_nav_packet"
	case CodecKlv:
		return "klv"
	case CodecOtf:
		return "otf"
	case CodecScte35:
		return "scte_35"
	case CodecTimedId3:
		return "timed_id3"
	case CodecTtf:
		return "ttf"
	case CodecAss:
		return "ass"
	case CodecDvbSubtitle:
		return "dvb_subtitle"
	case CodecDvbTeletext:
		return "dvb_teletext"
	case CodecDvdSubtitle:
		return "dvd_subtitle"
	case CodecEia608:
		return "eia_608"
	case CodecHdmvPgsSubtitle:
		return "hdmv_pgs_subtitle"
	case CodecHdmvTextSubtitle:
		return "hdmv_text_subtitle"
	case CodecJacosub:
		return "jacosub"
	case CodecMicrodvd:
		return "microdvd"
	case CodecMovText:
		return "mov_text"
	case CodecMpl2:
		return "mpl2"
	case CodecPjs:
		return "pjs"
	case CodecRealtext:
		return "realtext"
	case CodecSami:
		return "sami"
	case CodecSrt:
		return "srt"
	case CodecSsa:
		return "ssa"
	case CodecStl:
		return "stl"
	case CodecSubrip:
		return "subrip"
	case CodecSubviewer:
		return "subviewer"
	case CodecSubviewer1:
		return "subviewer1"
	case CodecText:
		return "text"
	case CodecVplayer:
		return "vplayer"
	case CodecWebvtt:
		return "webvtt"
	case CodecXsub:
		return "xsub"
	}
	return ""
}
