// Code generated by go generate; DO NOT EDIT.
// This code was generated by robots at
// 2017-11-28 11:51:45.190402252 +1100 AEDT m=+0.022946759

package ffmpeg

type FileFormat int

const (
	FileFormat3Dostr           FileFormat = iota // 3DO STR
	FileFormat3G2                                // 3GP2 (3GPP2 file format)
	FileFormat3Gp                                // 3GP (3GPP file format)
	FileFormat4Xm                                // 4X Technologies
	FileFormatA64                                // a64 - video for Commodore 64
	FileFormatAa                                 // Audible AA format files
	FileFormatAac                                // raw ADTS AAC (Advanced Audio Coding)
	FileFormatAc3                                // raw AC-3
	FileFormatAcm                                // Interplay ACM
	FileFormatAct                                // ACT Voice file format
	FileFormatAdf                                // Artworx Data Format
	FileFormatAdp                                // ADP
	FileFormatAds                                // Sony PS2 ADS
	FileFormatAdts                               // ADTS AAC (Advanced Audio Coding)
	FileFormatAdx                                // CRI ADX
	FileFormatAea                                // MD STUDIO audio
	FileFormatAfc                                // AFC
	FileFormatAiff                               // Audio IFF
	FileFormatAix                                // CRI AIX
	FileFormatAlaw                               // PCM A-law
	FileFormatAliasPix                           // Alias/Wavefront PIX image
	FileFormatAmr                                // 3GPP AMR
	FileFormatAnm                                // Deluxe Paint Animation
	FileFormatApc                                // CRYO APC
	FileFormatApe                                // Monkey's Audio
	FileFormatApng                               // Animated Portable Network Graphics
	FileFormatAqtitle                            // AQTitle subtitles
	FileFormatAsf                                // ASF (Advanced / Active Streaming Format)
	FileFormatAsfO                               // ASF (Advanced / Active Streaming Format)
	FileFormatAsfStream                          // ASF (Advanced / Active Streaming Format)
	FileFormatAss                                // SSA (SubStation Alpha) subtitle
	FileFormatAst                                // AST (Audio Stream)
	FileFormatAu                                 // Sun AU
	FileFormatAvfoundation                       // AVFoundation input device
	FileFormatAvi                                // AVI (Audio Video Interleaved)
	FileFormatAvm2                               // SWF (ShockWave Flash) (AVM2)
	FileFormatAvr                                // AVR (Audio Visual Research)
	FileFormatAvs                                // AVS
	FileFormatBethsoftvid                        // Bethesda Softworks VID
	FileFormatBfi                                // Brute Force & Ignorance
	FileFormatBfstm                              // BFSTM (Binary Cafe Stream)
	FileFormatBin                                // Binary text
	FileFormatBink                               // Bink
	FileFormatBit                                // G.729 BIT file format
	FileFormatBmpPipe                            // piped bmp sequence
	FileFormatBmv                                // Discworld II BMV
	FileFormatBoa                                // Black Ops Audio
	FileFormatBrenderPix                         // BRender PIX image
	FileFormatBrstm                              // BRSTM (Binary Revolution Stream)
	FileFormatC93                                // Interplay C93
	FileFormatCaf                                // Apple CAF (Core Audio Format)
	FileFormatCavsvideo                          // raw Chinese AVS (Audio Video Standard) video
	FileFormatCdg                                // CD Graphics
	FileFormatCdxl                               // Commodore CDXL video
	FileFormatCine                               // Phantom Cine
	FileFormatConcat                             // Virtual concatenation script
	FileFormatCrc                                // CRC testing
	FileFormatDash                               // DASH Muxer
	FileFormatData                               // raw data
	FileFormatDaud                               // D-Cinema audio
	FileFormatDcstr                              // Sega DC STR
	FileFormatDdsPipe                            // piped dds sequence
	FileFormatDfa                                // Chronomaster DFA
	FileFormatDirac                              // raw Dirac
	FileFormatDnxhd                              // raw DNxHD (SMPTE VC-3)
	FileFormatDpxPipe                            // piped dpx sequence
	FileFormatDsf                                // DSD Stream File (DSF)
	FileFormatDsicin                             // Delphine Software International CIN
	FileFormatDss                                // Digital Speech Standard (DSS)
	FileFormatDts                                // raw DTS
	FileFormatDtshd                              // raw DTS-HD
	FileFormatDv                                 // DV (Digital Video)
	FileFormatDvbsub                             // raw dvbsub
	FileFormatDvbtxt                             // dvbtxt
	FileFormatDvd                                // MPEG-2 PS (DVD VOB)
	FileFormatDxa                                // DXA
	FileFormatEa                                 // Electronic Arts Multimedia
	FileFormatEaCdata                            // Electronic Arts cdata
	FileFormatEac3                               // raw E-AC-3
	FileFormatEpaf                               // Ensoniq Paris Audio File
	FileFormatExrPipe                            // piped exr sequence
	FileFormatF32Be                              // PCM 32-bit floating-point big-endian
	FileFormatF32Le                              // PCM 32-bit floating-point little-endian
	FileFormatF4V                                // F4V Adobe Flash Video
	FileFormatF64Be                              // PCM 64-bit floating-point big-endian
	FileFormatF64Le                              // PCM 64-bit floating-point little-endian
	FileFormatFfm                                // FFM (FFserver live feed)
	FileFormatFfmetadata                         // FFmpeg metadata in text
	FileFormatFifo                               // FIFO queue pseudo-muxer
	FileFormatFilmCpk                            // Sega FILM / CPK
	FileFormatFilmstrip                          // Adobe Filmstrip
	FileFormatFits                               // Flexible Image Transport System
	FileFormatFlac                               // raw FLAC
	FileFormatFlic                               // FLI/FLC/FLX animation
	FileFormatFlv                                // FLV (Flash Video)
	FileFormatFramecrc                           // framecrc testing
	FileFormatFramehash                          // Per-frame hash testing
	FileFormatFramemd5                           // Per-frame MD5 testing
	FileFormatFrm                                // Megalux Frame
	FileFormatFsb                                // FMOD Sample Bank
	FileFormatG722                               // raw G.722
	FileFormatG7231                              // raw G.723.1
	FileFormatG726                               // raw big-endian G.726 ("left-justified")
	FileFormatG726Le                             // raw little-endian G.726 ("right-justified")
	FileFormatG729                               // G.729 raw format demuxer
	FileFormatGdv                                // Gremlin Digital Video
	FileFormatGenh                               // GENeric Header
	FileFormatGif                                // GIF Animation
	FileFormatGsm                                // raw GSM
	FileFormatGxf                                // GXF (General eXchange Format)
	FileFormatH261                               // raw H.261
	FileFormatH263                               // raw H.263
	FileFormatH264                               // raw H.264 video
	FileFormatHash                               // Hash testing
	FileFormatHds                                // HDS Muxer
	FileFormatHevc                               // raw HEVC video
	FileFormatHls                                // Apple HTTP Live Streaming
	FileFormatHnm                                // Cryo HNM v4
	FileFormatIco                                // Microsoft Windows ICO
	FileFormatIdcin                              // id Cinematic
	FileFormatIdf                                // iCE Draw File
	FileFormatIff                                // IFF (Interchange File Format)
	FileFormatIlbc                               // iLBC storage
	FileFormatImage2                             // image2 sequence
	FileFormatImage2Pipe                         // piped image2 sequence
	FileFormatIngenient                          // raw Ingenient MJPEG
	FileFormatIpmovie                            // Interplay MVE
	FileFormatIpod                               // iPod H.264 MP4 (MPEG-4 Part 14)
	FileFormatIrcam                              // Berkeley/IRCAM/CARL Sound Format
	FileFormatIsmv                               // ISMV/ISMA (Smooth Streaming)
	FileFormatIss                                // Funcom ISS
	FileFormatIv8                                // IndigoVision 8000 video
	FileFormatIvf                                // On2 IVF
	FileFormatIvr                                // IVR (Internet Video Recording)
	FileFormatJ2KPipe                            // piped j2k sequence
	FileFormatJacosub                            // JACOsub subtitle format
	FileFormatJpegPipe                           // piped jpeg sequence
	FileFormatJpeglsPipe                         // piped jpegls sequence
	FileFormatJv                                 // Bitmap Brothers JV
	FileFormatLatm                               // LOAS/LATM
	FileFormatLavfi                              // Libavfilter virtual input device
	FileFormatLiveFlv                            // live RTMP FLV (Flash Video)
	FileFormatLmlm4                              // raw lmlm4
	FileFormatLoas                               // LOAS AudioSyncStream
	FileFormatLrc                                // LRC lyrics
	FileFormatLvf                                // LVF
	FileFormatLxf                                // VR native stream (LXF)
	FileFormatM4V                                // raw MPEG-4 video
	FileFormatMatroska                           // Matroska
	FileFormatMd5                                // MD5 testing
	FileFormatMgsts                              // Metal Gear Solid: The Twin Snakes
	FileFormatMicrodvd                           // MicroDVD subtitle format
	FileFormatMjpeg                              // raw MJPEG video
	FileFormatMjpeg2000                          // raw MJPEG 2000 video
	FileFormatMkvtimestampV2                     // extract pts as timecode v2 format, as defined by mkvtoolnix
	FileFormatMlp                                // raw MLP
	FileFormatMlv                                // Magic Lantern Video (MLV)
	FileFormatMm                                 // American Laser Games MM
	FileFormatMmf                                // Yamaha SMAF
	FileFormatMov                                // QuickTime / MOV
	FileFormatMp2                                // MP2 (MPEG audio layer 2)
	FileFormatMp3                                // MP3 (MPEG audio layer 3)
	FileFormatMp4                                // MP4 (MPEG-4 Part 14)
	FileFormatMpc                                // Musepack
	FileFormatMpc8                               // Musepack SV8
	FileFormatMpeg                               // MPEG-1 Systems / MPEG program stream
	FileFormatMpeg1Video                         // raw MPEG-1 video
	FileFormatMpeg2Video                         // raw MPEG-2 video
	FileFormatMpegts                             // MPEG-TS (MPEG-2 Transport Stream)
	FileFormatMpegtsraw                          // raw MPEG-TS (MPEG-2 Transport Stream)
	FileFormatMpegvideo                          // raw MPEG video
	FileFormatMpjpeg                             // MIME multipart JPEG
	FileFormatMpl2                               // MPL2 subtitles
	FileFormatMpsub                              // MPlayer subtitles
	FileFormatMsf                                // Sony PS3 MSF
	FileFormatMsnwctcp                           // MSN TCP Webcam stream
	FileFormatMtaf                               // Konami PS2 MTAF
	FileFormatMtv                                // MTV
	FileFormatMulaw                              // PCM mu-law
	FileFormatMusx                               // Eurocom MUSX
	FileFormatMv                                 // Silicon Graphics Movie
	FileFormatMvi                                // Motion Pixels MVI
	FileFormatMxf                                // MXF (Material eXchange Format)
	FileFormatMxfD10                             // MXF (Material eXchange Format) D-10 Mapping
	FileFormatMxfOpatom                          // MXF (Material eXchange Format) Operational Pattern Atom
	FileFormatMxg                                // MxPEG clip
	FileFormatNc                                 // NC camera feed
	FileFormatNistsphere                         // NIST SPeech HEader REsources
	FileFormatNsv                                // Nullsoft Streaming Video
	FileFormatNull                               // raw null video
	FileFormatNut                                // NUT
	FileFormatNuv                                // NuppelVideo
	FileFormatOga                                // Ogg Audio
	FileFormatOgg                                // Ogg
	FileFormatOgv                                // Ogg Video
	FileFormatOma                                // Sony OpenMG audio
	FileFormatOpus                               // Ogg Opus
	FileFormatPaf                                // Amazing Studio Packed Animation File
	FileFormatPamPipe                            // piped pam sequence
	FileFormatPbmPipe                            // piped pbm sequence
	FileFormatPcxPipe                            // piped pcx sequence
	FileFormatPgmPipe                            // piped pgm sequence
	FileFormatPgmyuvPipe                         // piped pgmyuv sequence
	FileFormatPictorPipe                         // piped pictor sequence
	FileFormatPjs                                // PJS (Phoenix Japanimation Society) subtitles
	FileFormatPmp                                // Playstation Portable PMP
	FileFormatPngPipe                            // piped png sequence
	FileFormatPpmPipe                            // piped ppm sequence
	FileFormatPsdPipe                            // piped psd sequence
	FileFormatPsp                                // PSP MP4 (MPEG-4 Part 14)
	FileFormatPsxstr                             // Sony Playstation STR
	FileFormatPva                                // TechnoTrend PVA
	FileFormatPvf                                // PVF (Portable Voice Format)
	FileFormatQcp                                // QCP
	FileFormatQdrawPipe                          // piped qdraw sequence
	FileFormatR3D                                // REDCODE R3D
	FileFormatRawvideo                           // raw video
	FileFormatRealtext                           // RealText subtitle format
	FileFormatRedspark                           // RedSpark
	FileFormatRl2                                // RL2
	FileFormatRm                                 // RealMedia
	FileFormatRoq                                // raw id RoQ
	FileFormatRpl                                // RPL / ARMovie
	FileFormatRsd                                // GameCube RSD
	FileFormatRso                                // Lego Mindstorms RSO
	FileFormatRtp                                // RTP output
	FileFormatRtpMpegts                          // RTP/mpegts output format
	FileFormatRtsp                               // RTSP output
	FileFormatS16Be                              // PCM signed 16-bit big-endian
	FileFormatS16Le                              // PCM signed 16-bit little-endian
	FileFormatS24Be                              // PCM signed 24-bit big-endian
	FileFormatS24Le                              // PCM signed 24-bit little-endian
	FileFormatS32Be                              // PCM signed 32-bit big-endian
	FileFormatS32Le                              // PCM signed 32-bit little-endian
	FileFormatS337M                              // SMPTE 337M
	FileFormatS8                                 // PCM signed 8-bit
	FileFormatSami                               // SAMI subtitle format
	FileFormatSap                                // SAP output
	FileFormatSbg                                // SBaGen binaural beats script
	FileFormatScc                                // Scenarist Closed Captions
	FileFormatSdp                                // SDP
	FileFormatSdr2                               // SDR2
	FileFormatSds                                // MIDI Sample Dump Standard
	FileFormatSdx                                // Sample Dump eXchange
	FileFormatSegment                            // segment
	FileFormatSgiPipe                            // piped sgi sequence
	FileFormatShn                                // raw Shorten
	FileFormatSiff                               // Beam Software SIFF
	FileFormatSinglejpeg                         // JPEG single image
	FileFormatSln                                // Asterisk raw pcm
	FileFormatSmjpeg                             // Loki SDL MJPEG
	FileFormatSmk                                // Smacker
	FileFormatSmoothstreaming                    // Smooth Streaming Muxer
	FileFormatSmush                              // LucasArts Smush
	FileFormatSol                                // Sierra SOL
	FileFormatSox                                // SoX native
	FileFormatSpdif                              // IEC 61937 (used on S/PDIF - IEC958)
	FileFormatSpx                                // Ogg Speex
	FileFormatSrt                                // SubRip subtitle
	FileFormatStl                                // Spruce subtitle format
	FileFormatSubviewer                          // SubViewer subtitle format
	FileFormatSubviewer1                         // SubViewer v1 subtitle format
	FileFormatSunrastPipe                        // piped sunrast sequence
	FileFormatSup                                // raw HDMV Presentation Graphic Stream subtitles
	FileFormatSvag                               // Konami PS2 SVAG
	FileFormatSvcd                               // MPEG-2 PS (SVCD)
	FileFormatSvgPipe                            // piped svg sequence
	FileFormatSwf                                // SWF (ShockWave Flash)
	FileFormatTak                                // raw TAK
	FileFormatTedcaptions                        // TED Talks captions
	FileFormatTee                                // Multiple muxer tee
	FileFormatThp                                // THP
	FileFormatTiertexseq                         // Tiertex Limited SEQ
	FileFormatTiffPipe                           // piped tiff sequence
	FileFormatTmv                                // 8088flex TMV
	FileFormatTruehd                             // raw TrueHD
	FileFormatTta                                // TTA (True Audio)
	FileFormatTty                                // Tele-typewriter
	FileFormatTxd                                // Renderware TeXture Dictionary
	FileFormatU16Be                              // PCM unsigned 16-bit big-endian
	FileFormatU16Le                              // PCM unsigned 16-bit little-endian
	FileFormatU24Be                              // PCM unsigned 24-bit big-endian
	FileFormatU24Le                              // PCM unsigned 24-bit little-endian
	FileFormatU32Be                              // PCM unsigned 32-bit big-endian
	FileFormatU32Le                              // PCM unsigned 32-bit little-endian
	FileFormatU8                                 // PCM unsigned 8-bit
	FileFormatUncodedframecrc                    // uncoded framecrc testing
	FileFormatV210                               // Uncompressed 4:2:2 10-bit
	FileFormatV210X                              // Uncompressed 4:2:2 10-bit
	FileFormatVag                                // Sony PS2 VAG
	FileFormatVc1                                // raw VC-1 video
	FileFormatVc1Test                            // VC-1 test bitstream
	FileFormatVcd                                // MPEG-1 Systems / MPEG program stream (VCD)
	FileFormatVivo                               // Vivo
	FileFormatVmd                                // Sierra VMD
	FileFormatVob                                // MPEG-2 PS (VOB)
	FileFormatVobsub                             // VobSub subtitle format
	FileFormatVoc                                // Creative Voice
	FileFormatVpk                                // Sony PS2 VPK
	FileFormatVplayer                            // VPlayer subtitles
	FileFormatVqf                                // Nippon Telegraph and Telephone Corporation (NTT) TwinVQ
	FileFormatW64                                // Sony Wave64
	FileFormatWav                                // WAV / WAVE (Waveform Audio)
	FileFormatWc3Movie                           // Wing Commander III movie
	FileFormatWebm                               // WebM
	FileFormatWebmChunk                          // WebM Chunk Muxer
	FileFormatWebmDashManifest                   // WebM DASH Manifest
	FileFormatWebp                               // WebP
	FileFormatWebpPipe                           // piped webp sequence
	FileFormatWebvtt                             // WebVTT subtitle
	FileFormatWsaud                              // Westwood Studios audio
	FileFormatWsd                                // Wideband Single-bit Data (WSD)
	FileFormatWsvqa                              // Westwood Studios VQA
	FileFormatWtv                                // Windows Television (WTV)
	FileFormatWv                                 // raw WavPack
	FileFormatWve                                // Psion 3 audio
	FileFormatXa                                 // Maxis XA
	FileFormatXbin                               // eXtended BINary text (XBIN)
	FileFormatXmv                                // Microsoft XMV
	FileFormatXpmPipe                            // piped xpm sequence
	FileFormatXvag                               // Sony PS3 XVAG
	FileFormatXwma                               // Microsoft xWMA
	FileFormatYop                                // Psygnosis YOP
	FileFormatYuv4Mpegpipe                       // YUV4MPEG pipe
)

func (typ FileFormat) String() string {
	switch typ {
	case FileFormat3Dostr:
		return "3dostr"
	case FileFormat3G2:
		return "3g2"
	case FileFormat3Gp:
		return "3gp"
	case FileFormat4Xm:
		return "4xm"
	case FileFormatA64:
		return "a64"
	case FileFormatAa:
		return "aa"
	case FileFormatAac:
		return "aac"
	case FileFormatAc3:
		return "ac3"
	case FileFormatAcm:
		return "acm"
	case FileFormatAct:
		return "act"
	case FileFormatAdf:
		return "adf"
	case FileFormatAdp:
		return "adp"
	case FileFormatAds:
		return "ads"
	case FileFormatAdts:
		return "adts"
	case FileFormatAdx:
		return "adx"
	case FileFormatAea:
		return "aea"
	case FileFormatAfc:
		return "afc"
	case FileFormatAiff:
		return "aiff"
	case FileFormatAix:
		return "aix"
	case FileFormatAlaw:
		return "alaw"
	case FileFormatAliasPix:
		return "alias_pix"
	case FileFormatAmr:
		return "amr"
	case FileFormatAnm:
		return "anm"
	case FileFormatApc:
		return "apc"
	case FileFormatApe:
		return "ape"
	case FileFormatApng:
		return "apng"
	case FileFormatAqtitle:
		return "aqtitle"
	case FileFormatAsf:
		return "asf"
	case FileFormatAsfO:
		return "asf_o"
	case FileFormatAsfStream:
		return "asf_stream"
	case FileFormatAss:
		return "ass"
	case FileFormatAst:
		return "ast"
	case FileFormatAu:
		return "au"
	case FileFormatAvfoundation:
		return "avfoundation"
	case FileFormatAvi:
		return "avi"
	case FileFormatAvm2:
		return "avm2"
	case FileFormatAvr:
		return "avr"
	case FileFormatAvs:
		return "avs"
	case FileFormatBethsoftvid:
		return "bethsoftvid"
	case FileFormatBfi:
		return "bfi"
	case FileFormatBfstm:
		return "bfstm"
	case FileFormatBin:
		return "bin"
	case FileFormatBink:
		return "bink"
	case FileFormatBit:
		return "bit"
	case FileFormatBmpPipe:
		return "bmp_pipe"
	case FileFormatBmv:
		return "bmv"
	case FileFormatBoa:
		return "boa"
	case FileFormatBrenderPix:
		return "brender_pix"
	case FileFormatBrstm:
		return "brstm"
	case FileFormatC93:
		return "c93"
	case FileFormatCaf:
		return "caf"
	case FileFormatCavsvideo:
		return "cavsvideo"
	case FileFormatCdg:
		return "cdg"
	case FileFormatCdxl:
		return "cdxl"
	case FileFormatCine:
		return "cine"
	case FileFormatConcat:
		return "concat"
	case FileFormatCrc:
		return "crc"
	case FileFormatDash:
		return "dash"
	case FileFormatData:
		return "data"
	case FileFormatDaud:
		return "daud"
	case FileFormatDcstr:
		return "dcstr"
	case FileFormatDdsPipe:
		return "dds_pipe"
	case FileFormatDfa:
		return "dfa"
	case FileFormatDirac:
		return "dirac"
	case FileFormatDnxhd:
		return "dnxhd"
	case FileFormatDpxPipe:
		return "dpx_pipe"
	case FileFormatDsf:
		return "dsf"
	case FileFormatDsicin:
		return "dsicin"
	case FileFormatDss:
		return "dss"
	case FileFormatDts:
		return "dts"
	case FileFormatDtshd:
		return "dtshd"
	case FileFormatDv:
		return "dv"
	case FileFormatDvbsub:
		return "dvbsub"
	case FileFormatDvbtxt:
		return "dvbtxt"
	case FileFormatDvd:
		return "dvd"
	case FileFormatDxa:
		return "dxa"
	case FileFormatEa:
		return "ea"
	case FileFormatEaCdata:
		return "ea_cdata"
	case FileFormatEac3:
		return "eac3"
	case FileFormatEpaf:
		return "epaf"
	case FileFormatExrPipe:
		return "exr_pipe"
	case FileFormatF32Be:
		return "f32be"
	case FileFormatF32Le:
		return "f32le"
	case FileFormatF4V:
		return "f4v"
	case FileFormatF64Be:
		return "f64be"
	case FileFormatF64Le:
		return "f64le"
	case FileFormatFfm:
		return "ffm"
	case FileFormatFfmetadata:
		return "ffmetadata"
	case FileFormatFifo:
		return "fifo"
	case FileFormatFilmCpk:
		return "film_cpk"
	case FileFormatFilmstrip:
		return "filmstrip"
	case FileFormatFits:
		return "fits"
	case FileFormatFlac:
		return "flac"
	case FileFormatFlic:
		return "flic"
	case FileFormatFlv:
		return "flv"
	case FileFormatFramecrc:
		return "framecrc"
	case FileFormatFramehash:
		return "framehash"
	case FileFormatFramemd5:
		return "framemd5"
	case FileFormatFrm:
		return "frm"
	case FileFormatFsb:
		return "fsb"
	case FileFormatG722:
		return "g722"
	case FileFormatG7231:
		return "g723_1"
	case FileFormatG726:
		return "g726"
	case FileFormatG726Le:
		return "g726le"
	case FileFormatG729:
		return "g729"
	case FileFormatGdv:
		return "gdv"
	case FileFormatGenh:
		return "genh"
	case FileFormatGif:
		return "gif"
	case FileFormatGsm:
		return "gsm"
	case FileFormatGxf:
		return "gxf"
	case FileFormatH261:
		return "h261"
	case FileFormatH263:
		return "h263"
	case FileFormatH264:
		return "h264"
	case FileFormatHash:
		return "hash"
	case FileFormatHds:
		return "hds"
	case FileFormatHevc:
		return "hevc"
	case FileFormatHls:
		return "hls"
	case FileFormatHnm:
		return "hnm"
	case FileFormatIco:
		return "ico"
	case FileFormatIdcin:
		return "idcin"
	case FileFormatIdf:
		return "idf"
	case FileFormatIff:
		return "iff"
	case FileFormatIlbc:
		return "ilbc"
	case FileFormatImage2:
		return "image2"
	case FileFormatImage2Pipe:
		return "image2pipe"
	case FileFormatIngenient:
		return "ingenient"
	case FileFormatIpmovie:
		return "ipmovie"
	case FileFormatIpod:
		return "ipod"
	case FileFormatIrcam:
		return "ircam"
	case FileFormatIsmv:
		return "ismv"
	case FileFormatIss:
		return "iss"
	case FileFormatIv8:
		return "iv8"
	case FileFormatIvf:
		return "ivf"
	case FileFormatIvr:
		return "ivr"
	case FileFormatJ2KPipe:
		return "j2k_pipe"
	case FileFormatJacosub:
		return "jacosub"
	case FileFormatJpegPipe:
		return "jpeg_pipe"
	case FileFormatJpeglsPipe:
		return "jpegls_pipe"
	case FileFormatJv:
		return "jv"
	case FileFormatLatm:
		return "latm"
	case FileFormatLavfi:
		return "lavfi"
	case FileFormatLiveFlv:
		return "live_flv"
	case FileFormatLmlm4:
		return "lmlm4"
	case FileFormatLoas:
		return "loas"
	case FileFormatLrc:
		return "lrc"
	case FileFormatLvf:
		return "lvf"
	case FileFormatLxf:
		return "lxf"
	case FileFormatM4V:
		return "m4v"
	case FileFormatMatroska:
		return "matroska"
	case FileFormatMd5:
		return "md5"
	case FileFormatMgsts:
		return "mgsts"
	case FileFormatMicrodvd:
		return "microdvd"
	case FileFormatMjpeg:
		return "mjpeg"
	case FileFormatMjpeg2000:
		return "mjpeg_2000"
	case FileFormatMkvtimestampV2:
		return "mkvtimestamp_v2"
	case FileFormatMlp:
		return "mlp"
	case FileFormatMlv:
		return "mlv"
	case FileFormatMm:
		return "mm"
	case FileFormatMmf:
		return "mmf"
	case FileFormatMov:
		return "mov"
	case FileFormatMp2:
		return "mp2"
	case FileFormatMp3:
		return "mp3"
	case FileFormatMp4:
		return "mp4"
	case FileFormatMpc:
		return "mpc"
	case FileFormatMpc8:
		return "mpc8"
	case FileFormatMpeg:
		return "mpeg"
	case FileFormatMpeg1Video:
		return "mpeg1video"
	case FileFormatMpeg2Video:
		return "mpeg2video"
	case FileFormatMpegts:
		return "mpegts"
	case FileFormatMpegtsraw:
		return "mpegtsraw"
	case FileFormatMpegvideo:
		return "mpegvideo"
	case FileFormatMpjpeg:
		return "mpjpeg"
	case FileFormatMpl2:
		return "mpl2"
	case FileFormatMpsub:
		return "mpsub"
	case FileFormatMsf:
		return "msf"
	case FileFormatMsnwctcp:
		return "msnwctcp"
	case FileFormatMtaf:
		return "mtaf"
	case FileFormatMtv:
		return "mtv"
	case FileFormatMulaw:
		return "mulaw"
	case FileFormatMusx:
		return "musx"
	case FileFormatMv:
		return "mv"
	case FileFormatMvi:
		return "mvi"
	case FileFormatMxf:
		return "mxf"
	case FileFormatMxfD10:
		return "mxf_d10"
	case FileFormatMxfOpatom:
		return "mxf_opatom"
	case FileFormatMxg:
		return "mxg"
	case FileFormatNc:
		return "nc"
	case FileFormatNistsphere:
		return "nistsphere"
	case FileFormatNsv:
		return "nsv"
	case FileFormatNull:
		return "null"
	case FileFormatNut:
		return "nut"
	case FileFormatNuv:
		return "nuv"
	case FileFormatOga:
		return "oga"
	case FileFormatOgg:
		return "ogg"
	case FileFormatOgv:
		return "ogv"
	case FileFormatOma:
		return "oma"
	case FileFormatOpus:
		return "opus"
	case FileFormatPaf:
		return "paf"
	case FileFormatPamPipe:
		return "pam_pipe"
	case FileFormatPbmPipe:
		return "pbm_pipe"
	case FileFormatPcxPipe:
		return "pcx_pipe"
	case FileFormatPgmPipe:
		return "pgm_pipe"
	case FileFormatPgmyuvPipe:
		return "pgmyuv_pipe"
	case FileFormatPictorPipe:
		return "pictor_pipe"
	case FileFormatPjs:
		return "pjs"
	case FileFormatPmp:
		return "pmp"
	case FileFormatPngPipe:
		return "png_pipe"
	case FileFormatPpmPipe:
		return "ppm_pipe"
	case FileFormatPsdPipe:
		return "psd_pipe"
	case FileFormatPsp:
		return "psp"
	case FileFormatPsxstr:
		return "psxstr"
	case FileFormatPva:
		return "pva"
	case FileFormatPvf:
		return "pvf"
	case FileFormatQcp:
		return "qcp"
	case FileFormatQdrawPipe:
		return "qdraw_pipe"
	case FileFormatR3D:
		return "r3d"
	case FileFormatRawvideo:
		return "rawvideo"
	case FileFormatRealtext:
		return "realtext"
	case FileFormatRedspark:
		return "redspark"
	case FileFormatRl2:
		return "rl2"
	case FileFormatRm:
		return "rm"
	case FileFormatRoq:
		return "roq"
	case FileFormatRpl:
		return "rpl"
	case FileFormatRsd:
		return "rsd"
	case FileFormatRso:
		return "rso"
	case FileFormatRtp:
		return "rtp"
	case FileFormatRtpMpegts:
		return "rtp_mpegts"
	case FileFormatRtsp:
		return "rtsp"
	case FileFormatS16Be:
		return "s16be"
	case FileFormatS16Le:
		return "s16le"
	case FileFormatS24Be:
		return "s24be"
	case FileFormatS24Le:
		return "s24le"
	case FileFormatS32Be:
		return "s32be"
	case FileFormatS32Le:
		return "s32le"
	case FileFormatS337M:
		return "s337m"
	case FileFormatS8:
		return "s8"
	case FileFormatSami:
		return "sami"
	case FileFormatSap:
		return "sap"
	case FileFormatSbg:
		return "sbg"
	case FileFormatScc:
		return "scc"
	case FileFormatSdp:
		return "sdp"
	case FileFormatSdr2:
		return "sdr2"
	case FileFormatSds:
		return "sds"
	case FileFormatSdx:
		return "sdx"
	case FileFormatSegment:
		return "segment"
	case FileFormatSgiPipe:
		return "sgi_pipe"
	case FileFormatShn:
		return "shn"
	case FileFormatSiff:
		return "siff"
	case FileFormatSinglejpeg:
		return "singlejpeg"
	case FileFormatSln:
		return "sln"
	case FileFormatSmjpeg:
		return "smjpeg"
	case FileFormatSmk:
		return "smk"
	case FileFormatSmoothstreaming:
		return "smoothstreaming"
	case FileFormatSmush:
		return "smush"
	case FileFormatSol:
		return "sol"
	case FileFormatSox:
		return "sox"
	case FileFormatSpdif:
		return "spdif"
	case FileFormatSpx:
		return "spx"
	case FileFormatSrt:
		return "srt"
	case FileFormatStl:
		return "stl"
	case FileFormatSubviewer:
		return "subviewer"
	case FileFormatSubviewer1:
		return "subviewer1"
	case FileFormatSunrastPipe:
		return "sunrast_pipe"
	case FileFormatSup:
		return "sup"
	case FileFormatSvag:
		return "svag"
	case FileFormatSvcd:
		return "svcd"
	case FileFormatSvgPipe:
		return "svg_pipe"
	case FileFormatSwf:
		return "swf"
	case FileFormatTak:
		return "tak"
	case FileFormatTedcaptions:
		return "tedcaptions"
	case FileFormatTee:
		return "tee"
	case FileFormatThp:
		return "thp"
	case FileFormatTiertexseq:
		return "tiertexseq"
	case FileFormatTiffPipe:
		return "tiff_pipe"
	case FileFormatTmv:
		return "tmv"
	case FileFormatTruehd:
		return "truehd"
	case FileFormatTta:
		return "tta"
	case FileFormatTty:
		return "tty"
	case FileFormatTxd:
		return "txd"
	case FileFormatU16Be:
		return "u16be"
	case FileFormatU16Le:
		return "u16le"
	case FileFormatU24Be:
		return "u24be"
	case FileFormatU24Le:
		return "u24le"
	case FileFormatU32Be:
		return "u32be"
	case FileFormatU32Le:
		return "u32le"
	case FileFormatU8:
		return "u8"
	case FileFormatUncodedframecrc:
		return "uncodedframecrc"
	case FileFormatV210:
		return "v210"
	case FileFormatV210X:
		return "v210x"
	case FileFormatVag:
		return "vag"
	case FileFormatVc1:
		return "vc1"
	case FileFormatVc1Test:
		return "vc1test"
	case FileFormatVcd:
		return "vcd"
	case FileFormatVivo:
		return "vivo"
	case FileFormatVmd:
		return "vmd"
	case FileFormatVob:
		return "vob"
	case FileFormatVobsub:
		return "vobsub"
	case FileFormatVoc:
		return "voc"
	case FileFormatVpk:
		return "vpk"
	case FileFormatVplayer:
		return "vplayer"
	case FileFormatVqf:
		return "vqf"
	case FileFormatW64:
		return "w64"
	case FileFormatWav:
		return "wav"
	case FileFormatWc3Movie:
		return "wc3movie"
	case FileFormatWebm:
		return "webm"
	case FileFormatWebmChunk:
		return "webm_chunk"
	case FileFormatWebmDashManifest:
		return "webm_dash_manifest"
	case FileFormatWebp:
		return "webp"
	case FileFormatWebpPipe:
		return "webp_pipe"
	case FileFormatWebvtt:
		return "webvtt"
	case FileFormatWsaud:
		return "wsaud"
	case FileFormatWsd:
		return "wsd"
	case FileFormatWsvqa:
		return "wsvqa"
	case FileFormatWtv:
		return "wtv"
	case FileFormatWv:
		return "wv"
	case FileFormatWve:
		return "wve"
	case FileFormatXa:
		return "xa"
	case FileFormatXbin:
		return "xbin"
	case FileFormatXmv:
		return "xmv"
	case FileFormatXpmPipe:
		return "xpm_pipe"
	case FileFormatXvag:
		return "xvag"
	case FileFormatXwma:
		return "xwma"
	case FileFormatYop:
		return "yop"
	case FileFormatYuv4Mpegpipe:
		return "yuv4mpegpipe"
	}
	return ""
}
